# Generated by Django 4.0.3 on 2022-12-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0004_folder_folder_alter_folder_public_alter_folder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fmsApp.folder'),
        ),
    ]
