# Generated by Django 4.0.3 on 2022-12-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0005_post_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='on_page',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='on_page',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
